/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordingIdRouteImport } from './routes/$recordingId'
import { Route as IndexRouteImport } from './routes/index'

const RecordingIdRoute = RecordingIdRouteImport.update({
  id: '/$recordingId',
  path: '/$recordingId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$recordingId': typeof RecordingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$recordingId': typeof RecordingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$recordingId': typeof RecordingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$recordingId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$recordingId'
  id: '__root__' | '/' | '/$recordingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordingIdRoute: typeof RecordingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$recordingId': {
      id: '/$recordingId'
      path: '/$recordingId'
      fullPath: '/$recordingId'
      preLoaderRoute: typeof RecordingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordingIdRoute: RecordingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
